import { ArrowDown, ArrowUpRight, CodeXml, Mail, Copy } from 'lucide-react';
import { Header, Footer } from '@/components/site';


const papers = [
  {name:'ParallelWorld',subtitle:'Test-Time Scaling for Embodied Reasoning',category:'EMBODIED REASONING',image:'parallelworld.png',alt:'ParallelWorld method: parallel future trajectories and verifier-guided selection',paper:'https://arxiv.org/abs/2608.22971',project:'https://chen-min-22.github.io/ParallelWorld-page/',description:'Exploring multiple possible futures before taking the next step. A framework for embodied reasoning through parallel, multi-step simulation and verifier-guided search.',authors:'Min Chen, Shengjun Zhang, Yuxin Li, Zhang Zhang, Xin Fei, Chong Xia, Yueqi Duan'},
  {name:'MBench',subtitle:'A Comprehensive Benchmark on Memory Capability for Video World Models',category:'WORLD MODELS · EVALUATION',image:'mbench.jpg',alt:'MBench taxonomy of entity, environment, and causal consistency',paper:'https://arxiv.org/abs/2606.00793',project:'https://peanutup.github.io/MBench-project/',code:'https://github.com/study-overflow/MBench',description:'What does a generated world remember? Evaluating long-term memory through entity, environment, and causal consistency across 12 dimensions.',authors:'Shengjun Zhang, Zhang Zhang, Simin Huang, Zhenyu Tang, Hanyang Wang, Chensheng Dai, Min Chen, Yifan Li, Yuxin Li, Yingjie Chen, Hao Liu, Chen Li, Jing Lyu, Yueqi Duan'}
];
export default function Home() {
  return <div id="top">

    <Header/>
    <main id="main" className="wrap">
      <section className="hero" aria-labelledby="name">
        <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> TSINGHUA UNIVERSITY · BEIJING</p><h1 id="name">Yuxin Li<span className="accent">.</span></h1><p className="hero-subtitle">Learning to see.<br/><em>Building worlds that remember.</em></p><p className="intro">I’m an undergraduate at <strong>Tsinghua University</strong>, in Xinya College and the Department of Electronic Engineering. I work on computer vision, world models, and harnesses.</p><div className="hero-links"><a className="primary-link" href="/publications/">Explore my research <ArrowDown size={16}/></a><a href="https://github.com/Cx300-fh" target="_blank" rel="noreferrer"><CodeXml size={17}/> GitHub <ArrowUpRight size={14}/></a><a href="mailto:li-yx24@mails.tsinghua.edu.cn"><Mail size={17}/> Email</a></div></div>
        <div className="avatar-area"><figure className="polaroid portrait"><img src="/images/yuxin-li.jpg" alt="Portrait of Yuxin Li" width="1280" height="1831"/><figcaption>A little curiosity goes a long way.</figcaption></figure><span className="avatar-note">Yuxin Li · Tsinghua University</span><span className="avatar-index">PERSONAL FIELD NOTES / 01</span></div>
      </section>
      <div className="interest-strip"><span className="eyebrow">THINKING ABOUT</span><p>Computer Vision <span>↗</span> World Models <span>↗</span> Harnesses</p><span className="strip-number">01 — 03</span></div>
      <section id="research" className="section research" aria-labelledby="research-heading"><div className="section-heading"><div><p className="eyebrow">01 / RESEARCH</p><h2 id="research-heading">Selected work<span className="accent">.</span></h2></div><a className="text-link" href="/publications/">All publications <ArrowUpRight size={16}/></a></div>
        {papers.map(p=><article className="paper" key={p.name}><a className={`paper-visual ${p.name==='MBench'?'mbench':''}`} href={p.project} target="_blank" rel="noreferrer" aria-label={`${p.name} project page`}><img src={`/images/${p.image}`} alt={p.alt} loading="lazy"/></a><div className="paper-copy"><p className="paper-meta">2026 <span>/</span> {p.category}</p><h3><a href={p.paper} target="_blank" rel="noreferrer">{p.name}<ArrowUpRight/></a></h3><p className="paper-subtitle">{p.subtitle}</p><p className="paper-description">{p.description}</p><p className="authors">{p.authors.split('Yuxin Li')[0]}<strong>Yuxin Li</strong>{p.authors.split('Yuxin Li')[1]}</p><div className="paper-links"><a href={p.paper} target="_blank" rel="noreferrer">Paper <ArrowUpRight size={14}/></a><a href={p.project} target="_blank" rel="noreferrer">Project page <ArrowUpRight size={14}/></a>{p.code&&<a href={p.code} target="_blank" rel="noreferrer">Code <ArrowUpRight size={14}/></a>}</div></div></article>)}
      </section>
      <section id="about" className="section about"><div className="section-heading"><div><p className="eyebrow">02 / A LITTLE CONTEXT</p><h2>About me<span className="accent">.</span></h2></div></div><div className="about-grid"><div><p className="about-lead">From perception to prediction,<br/>and from simulation to the real world.</p><p className="about-text">My research interests connect computer vision, world models, and embodied intelligence. I’m currently working with Prof. Yueqi Duan’s group at Tsinghua University on video generation and world models.</p><p className="about-text">Alongside research, I’ve built and trained navigation policies for quadruped robots, explored time-series forecasting with large language models, and worked on perception experiments. I also help produce stories with Tsinghua’s student media team.</p><a className="text-link" href="/cv/" target="_blank" rel="noreferrer">View my curriculum vitae <ArrowUpRight size={16}/></a></div><aside className="background-notes"><p className="eyebrow">EDUCATION</p><p className="school">Tsinghua University</p><p>Undergraduate<br/>Xinya College<br/>Department of Electronic Engineering</p><div className="skills"><p className="eyebrow">TOOLS OF THE TRADE</p><p>Python · C++ · PyTorch<br/>Reinforcement learning · PPO<br/>Robot navigation · Git</p></div></aside></div>
      </section>
      <section className="contact" aria-labelledby="contact-heading"><p className="eyebrow">ALWAYS CURIOUS</p><h2 id="contact-heading">Let’s compare notes<span className="accent">.</span></h2><p>On vision, world models, or something worth building.</p><div className="contact-links"><a href="mailto:li-yx24@mails.tsinghua.edu.cn">li-yx24@mails.tsinghua.edu.cn <ArrowUpRight size={20}/></a><button type="button" className="copy-email" aria-label="Copy email address" data-copy-email><Copy size={16}/></button><span role="status" className="copy-status"/></div></section>
    </main><Footer/>
  </div>;
}
