export const papers = [
  {name:'ParallelWorld',slug:'parallelworld',subtitle:'Test-Time Scaling for Embodied Reasoning',category:'EMBODIED REASONING',image:'parallelworld.png',alt:'ParallelWorld method: parallel future trajectories and verifier-guided selection',paper:'https://arxiv.org/abs/2608.22971',project:'https://chen-min-22.github.io/ParallelWorld-page/',code:undefined,description:'A framework for embodied reasoning through parallel, multi-step simulation and verifier-guided search.',authors:'Min Chen, Shengjun Zhang, Yuxin Li, Zhang Zhang, Xin Fei, Chong Xia, Yueqi Duan',tags:['Embodied reasoning','Test-time scaling'],month:'AUG 2026'},
  {name:'MBench',slug:'mbench',subtitle:'A Comprehensive Benchmark on Memory Capability for Video World Models',category:'WORLD MODELS · EVALUATION',image:'mbench.jpg',alt:'MBench taxonomy of entity, environment, and causal consistency',paper:'https://arxiv.org/abs/2606.00793',project:'https://peanutup.github.io/MBench-project/',code:'https://github.com/study-overflow/MBench',description:'Evaluating long-term memory through entity, environment, and causal consistency across 12 dimensions.',authors:'Shengjun Zhang, Zhang Zhang, Simin Huang, Zhenyu Tang, Hanyang Wang, Chensheng Dai, Min Chen, Yifan Li, Yuxin Li, Yingjie Chen, Hao Liu, Chen Li, Jing Lyu, Yueqi Duan',tags:['World models','Memory','Evaluation'],month:'MAY 2026'}
];
export const projects = [
  {slug:'quadruped-navigation',name:'Quadruped navigation',category:'EMBODIED INTELLIGENCE',date:'JUN — OCT 2025',image:'navigation.svg',alt:'Workflow diagram connecting PPO policy training, simulation, and real-robot navigation',description:'PPO policies for obstacle avoidance and path planning on varied terrain, from simulation to deployment on real robots.',result:'13th in semifinals · 25th in finals',event:'Tencent AI Open · Embodied Intelligence Track',tags:['PPO','Sim-to-real','Robot navigation'],details:['Developed navigation and obstacle-avoidance policies, including reward design and PPO network tuning.','Iterated through policy training in simulation and adapted the system for deployment on a quadruped robot.','Worked on terrain variation, local optima, and hardware integration during the competition.']},
  {slug:'multi-agent-control',name:'Intelligent games & multi-agent control',category:'MULTI-AGENT SYSTEMS',date:'MAY 2026',image:'multi-agent.svg',alt:'Conceptual diagram of multiple agents coordinating around a shared task',description:'Independent development across two competition tracks, exploring intelligent games and collaborative control.',result:'Third prize in both tracks',event:'THUAI9 Artificial Intelligence Challenge · Tsinghua University',tags:['Multi-agent systems','Decision-making'],details:['Completed development independently across both the intelligent-games and multi-agent collaborative-control tracks.','Built models, debugged the implementation, and iterated on strategies for both competition tasks.']},
  {slug:'embedded-hardware',name:'From board to working system',category:'EMBEDDED SYSTEMS',date:'JUL — SEP 2025',image:'hardware.svg',alt:'Workflow diagram from PCB debugging through drivers to hardware-software integration',description:'Embedded hardware development, PCB debugging, low-level drivers, and hardware–software integration.',result:'Merit Award',event:'Electronic Engineering Hardware Design Competition · Tsinghua University',tags:['Embedded systems','C++','Hardware'],details:['Worked with a team on an embedded hardware solution, from component selection to an integrated prototype.','Contributed circuit testing, low-level logic debugging, driver development, and system integration.']}
];
export const experience = [
  {date:'FEB 2026 — PRESENT',title:'Video generation & world models',affiliation:'Prof. Yueqi Duan · Tsinghua University',text:'Research in 3D computer vision, spatial intelligence, and world models, including MBench and ParallelWorld.'},
  {date:'OCT 2025 — PRESENT',title:'Future prediction with large models',affiliation:'Prof. Yong Li · Student Research Training',text:'Time-series input design, prompting, data preparation, and evaluation for forecasting with large language models.'},
  {date:'MAR — JUN 2025',title:'Cognition & olfactory perception',affiliation:'Future Laboratory · Tsinghua University',text:'Designed controlled experiments, collected behavioral data, and performed statistical analysis to study how self-selected scents affect code compilation performance.'}
];
