import { ArrowUpRight } from 'lucide-react';
import { PageShell } from '@/components/site';
import './essay.css';

export const metadata={title:'From Reasoning to Muscle Memory — Yuxin Li',description:'GPT-6 Astra, System 2, VLA skill learning, and the missing path from reasoning to embodied reflex.'};

const Box=({title,sub,kind=''}:{title:string;sub:string;kind?:string})=><div className={`essay-box ${kind}`}><strong>{title}</strong><span>{sub}</span></div>;
const Link=({href,children}:{href:string;children:React.ReactNode})=><a className="essay-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={13}/></a>;
export default function Post(){return <PageShell active="Blog" eyebrow="RESEARCH NOTE / EMBODIED INTELLIGENCE" title="From Reasoning to Muscle Memory" description="GPT-6 Astra may be a powerful brain for a robot. That does not mean the brain should control every millisecond of its body."><article className="research-essay"><div className="essay-meta">SEPTEMBER 15, 2026 · 14 MIN READ · YUXIN LI</div><p className="essay-lede">Recent robot experiments with GPT-6 Astra suggest a more useful question than “Will a frontier model replace the VLA?” Embodied systems live under hard latency, bandwidth, contact and embodiment constraints. A general model can plausibly become the system that solves a task the <em>first</em> time, while repeated experience is distilled into progressively faster policies. The missing research problem is therefore not only better reasoning, but <strong>how reasoning becomes skill, and how skill becomes reflex.</strong></p>
<figure className="essay-figure hero-figure"><div className="skill-spectrum"><div><span>Novel task</span><Box title="SYSTEM 2" sub="Reason · Explore · Recover" kind="s2"/><small>Frontier Agent / GPT-N</small></div><b>→</b><div><span>Learned skill</span><Box title="SYSTEM 1" sub="Fast visuomotor policy" kind="s1"/><small>VLA / Skill Policy</small></div><b>→</b><div><span>Muscle memory</span><Box title="SYSTEM 0" sub="Local · Reactive · Stable" kind="s0"/><small>Motor Prior / Controller</small></div></div><div className="spectrum-axis"><span>slow · general · expensive</span><i></i><span>fast · embodied · cheap</span></div><figcaption><b>Fig. 1 | The core hypothesis.</b> Intelligence should migrate downward as a task becomes familiar. System 2 is valuable precisely because it does not have to remain in the loop forever.</figcaption></figure>
<h2>Astra looks more like a first-time problem solver than a real-time controller</h2><p>RoboCurve gives an unusually concrete view of what “GPT controls a robot” currently means. Astra receives three RGB views plus proprioception and emits absolute Cartesian end-effector targets. Inverse kinematics and the robot’s lower-level controller still sit between the language model and the motors. On the coarse block-to-bowl task Astra succeeds in 19/20 trials, while on precision puzzle insertion it succeeds in only 2/20. The contrast matters more than the headline success rate: semantic understanding, spatial reasoning and low-frequency correction have scaled much further than contact-rich servoing.</p>
<figure className="essay-figure"><div className="pipeline"><Box title="3× RGB + proprio" sub="Observation"/><b>→</b><Box title="GPT-6 Astra" sub="reason / plan / recover" kind="s2"/><b>→</b><Box title="EE pose" sub="x y z · RPY · gripper"/><b>→</b><Box title="IK + controller" sub="joint-level execution" kind="s0"/><b>→</b><Box title="Robot" sub="new observation"/></div><div className="evidence-row"><div><strong>95%</strong><span>Block → bowl<br/>19 / 20</span></div><div className="cliff">capability cliff →</div><div><strong>10%</strong><span>Puzzle insertion<br/>2 / 20</span></div></div><figcaption><b>Fig. 2 | What RoboCurve actually demonstrates.</b> Astra is a closed-loop high-level visuomotor agent, not a torque policy. Its precision-task drop exposes the boundary between deliberative intelligence and fast physical competence. <Link href="https://openai.robocurve.org/gpt-6-astra/">Experiment</Link></figcaption></figure>
<p>ARC Prize’s Astra evaluation reinforces the other side of this picture. In unfamiliar interactive environments the model explores, records state, infers rules and constructs compact internal representations before acting efficiently. That is strikingly System-2-like: the model is useful when the rules are not yet known. ARC reports that Astra uses fewer actions than the human median on 96% of levels. <Link href="https://arcprize.org/blog/astra">ARC Prize analysis</Link></p>
<figure className="essay-figure"><div className="arc-loop"><Box title="Unknown environment" sub="no task-specific training"/><b>→</b><Box title="Interact" sub="probe the environment"/><b>→</b><Box title="Infer rules" sub="state · objects · transitions" kind="s2"/><b>→</b><Box title="Compact model" sub="shorthand / symbolic state"/><b>→</b><Box title="Plan" sub="action-efficient solution"/></div><figcaption><b>Fig. 3 | The zero-shot role.</b> A frontier agent is most valuable at the left edge of the learning curve: when a robot does not yet possess a task-specific skill.</figcaption></figure>
<h2>The hierarchy already exists. The missing part is learning across it.</h2><p>Robotics already provides strong engineering evidence that these time scales should be separated. Figure’s Helix family explicitly divides semantic reasoning, visuomotor behavior and high-frequency whole-body control; other humanoid stacks similarly place fast learned controllers beneath slower task-level intelligence. This is not merely a cognitive-science metaphor. A robot cannot wait for a remote frontier model while resolving balance, collision or contact transients.</p>
<figure className="essay-figure split-figure"><div><div className="figure-label">EXECUTION HIERARCHY · TODAY</div><Box title="System 2" sub="What should I do?" kind="s2"/><div className="down">↓ goal / intent</div><Box title="System 1" sub="How do I manipulate?" kind="s1"/><div className="down">↓ motor targets</div><Box title="System 0" sub="How do I remain stable?" kind="s0"/></div><div className="missing"><div className="figure-label">LEARNING HIERARCHY · MISSING</div><Box title="System 2" sub="first successful exploration" kind="s2"/><div className="down accent-down">⇓ consolidate experience</div><Box title="System 1" sub="learned reusable skill" kind="s1"/><div className="down accent-down">⇓ repeated practice</div><Box title="System 0" sub="embodied motor prior" kind="s0"/></div><figcaption><b>Fig. 4 | Execution is not consolidation.</b> Existing hierarchical systems tell us how information flows downward during execution. The open problem is how a newly solved task itself migrates from slow reasoning into faster policies.</figcaption></figure>
<p>This changes how I interpret imitation learning. Historically, a human teleoperator often acts as the external System 2: understand the task, explore the correct motion, provide demonstrations, then let the policy imitate them. If a frontier model can now zero-shot explore some tasks, its first successful trajectory can become a new source of embodied experience. But naïvely cloning the entire trajectory is wrong: first attempts contain hesitation, failed grasps, backtracking and unnecessary probes. A learner should acquire the <em>solution</em>, not imitate the teacher’s confusion.</p>
<figure className="essay-figure"><div className="consolidation"><div className="trace"><span>GPT-N exploration trace</span><i>probe</i><i className="bad">failed grasp</i><i>re-localize</i><i>grasp</i><i className="bad">backtrack</i><i>lift</i><i>place</i></div><div className="compress">EXPERIENCE CONSOLIDATION<br/><small>failure filtering · subgoal extraction · recovery retention · compression</small><b>↓</b></div><div className="trace clean"><span>Reusable skill</span><i>localize</i><i>grasp</i><i>lift</i><i>place</i></div></div><figcaption><b>Fig. 5 | Do not behavior-clone exploration literally.</b> The research object is a consolidation operator C that maps a costly exploratory trajectory into a compact, robust skill while preserving useful recovery behavior.</figcaption></figure>
<h2>World models may matter more for learning than for acting</h2><p>The same argument changes the role of a world model. Permanently generating future video before every familiar action is difficult to justify under real-time constraints. But during first-time learning, counterfactual imagination is unusually valuable: real trials are slow, irreversible and sometimes unsafe. System 2 can propose alternatives, a world model can cheaply expose their likely consequences, and only selected hypotheses need real-world verification.</p>
<figure className="essay-figure"><div className="wm-layout"><div><Box title="SYSTEM 2 · GPT-N" sub="propose candidate strategies" kind="s2"/><div className="down">↓ a₁ · a₂ · a₃</div><Box title="WORLD MODEL" sub="counterfactual practice" kind="wm"/><div className="branches"><span>future 1</span><span>future 2</span><span>future 3</span></div></div><b>→</b><div><Box title="REAL ROBOT" sub="verify selected hypothesis"/><div className="down accent-down">⇓ experience</div><Box title="CONSOLIDATE" sub="train / adapt skill"/><div className="down accent-down">⇓</div><Box title="SYSTEM 1" sub="deploy without imagination" kind="s1"/></div></div><figcaption><b>Fig. 6 | World model as a practice environment.</b> The world model is most valuable where uncertainty is high and experience is scarce. Once a behavior is consolidated, the expensive imagination loop can disappear from routine execution.</figcaption></figure>
<p>The resulting compute path is adaptive rather than fixed. A novel task may invoke <strong>S2 + world model + S1 + S0</strong>; a learned task can run mostly through <strong>S1 + S0</strong>; highly practiced stabilization and motor behavior can be handled locally. Zero-shot success then stops being the endpoint of robotics and becomes the beginning of skill acquisition.</p>
<figure className="essay-figure"><div className="learning-curve"><div className="curve-head"><span>Novel</span><span>Familiar</span></div><div className="curve-track"><div className="band b2"><b>System 2</b><span>high at first · fades with familiarity</span></div><div className="band bw"><b>World Model</b><span>counterfactual practice when uncertainty is high</span></div><div className="band b1"><b>System 1</b><span>grows as reusable visuomotor skill is acquired</span></div><div className="band b0"><b>System 0</b><span>persistent fast embodiment-specific control</span></div></div></div><figcaption><b>Fig. 7 | Compute should follow familiarity.</b> A mature embodied agent should not spend frontier-model inference on behavior it has already mastered.</figcaption></figure>
<p className="essay-conclusion">The strongest version of this hypothesis is simple: <strong>a robot should think hard once, learn from that thinking, and gradually stop thinking about what has become routine.</strong> GPT-6 Astra makes the first arrow plausible. Hierarchical robot systems make the latency argument concrete. What remains largely unsolved are the two downward learning arrows: <em>reasoning → skill → muscle memory</em>. If GPT-7 makes first-time task reasoning cheap and broadly available, those arrows become more—not less—important.</p><div className="essay-resources"><span>EXPERIMENTS / FURTHER READING</span><Link href="https://openai.robocurve.org/gpt-6-astra/">RoboCurve · GPT-6 Astra on robot arms</Link><Link href="https://arcprize.org/blog/astra">ARC Prize · Astra in unfamiliar interactive worlds</Link><Link href="https://www.figure.ai/news/helix-02">Figure · Helix 02</Link><Link href="https://anonymous-report-421.github.io/public-website/?lang=zh&view=1">Community report · frontier agents for embodied systems</Link></div></article></PageShell>}
